######################################################################
# Automatically generated by qmake (3.0) Sun Apr 10 02:51:41 2016
######################################################################

TEMPLATE = app
TARGET = linux_peripheral
INCLUDEPATH += .

CONFIGURE += qt c++11

# Input
HEADERS += BLEPeripheral.h
SOURCES += BLEPeripheral.cpp main.cpp
QT -= GUI
QT += bluetooth
